# Generated by Django 3.2 on 2022-04-18 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_auto_20220418_1640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productentity',
            options={'verbose_name': 'заказаннй продукт', 'verbose_name_plural': 'заказанные продукты'},
        ),
    ]
