# Generated by Django 3.2 on 2022-04-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_auto_20220419_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='productentity',
            name='price',
            field=models.DecimalField(decimal_places=10, max_digits=19, null=True, verbose_name='Цена позиции'),
        ),
    ]
