# Generated by Django 3.2 on 2022-04-21 17:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_alter_productentity_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productentity',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Цена позиции'),
        ),
    ]
