# Generated by Django 3.2 on 2022-04-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_alter_productentity_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processed', 'Обработан'), ('unprocessed', 'Не обработан')], db_index=True, default='unprocessed', max_length=25),
        ),
    ]
