# Generated by Django 3.2 on 2022-04-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, verbose_name='коментарий к заказу'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processed', 'Обработан'), ('unprocessed', 'Не обработан')], db_index=True, default='unprocessed', max_length=25, verbose_name='статус заказа'),
        ),
    ]
