# Generated by Django 3.2 on 2022-04-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_order_call_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('card', 'Электронно'), ('unknown', 'Не указано')], db_index=True, default='unknown', max_length=25, verbose_name='способ оплаты'),
        ),
    ]
