# Generated by Django 3.2 on 2022-04-22 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reestaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodcartapp.restaurant', verbose_name='Ресторан'),
        ),
    ]
