# Generated by Django 3.2 on 2022-04-22 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_order_reestaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='reestaurant',
            new_name='restaurant',
        ),
    ]
