# Generated by Django 3.2 on 2022-04-23 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0057_auto_20220423_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productentity',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='foodcartapp.product', verbose_name='Продукт'),
        ),
    ]
