# Generated by Django 3.2 on 2022-04-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0058_alter_productentity_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='restaurants',
            field=models.ManyToManyField(blank=True, db_index=True, null=True, to='foodcartapp.Restaurant', verbose_name='Ресторан'),
        ),
    ]
