# Generated by Django 3.2 on 2022-04-24 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cords', '0002_auto_20220424_1317'),
        ('foodcartapp', '0059_alter_order_restaurants'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='map_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place', to='cords.point', verbose_name='Точка на карте'),
        ),
        migrations.AlterField(
            model_name='order',
            name='restaurants',
            field=models.ManyToManyField(blank=True, null=True, to='foodcartapp.Restaurant', verbose_name='Ресторан'),
        ),
    ]
