# Generated by Django 3.2 on 2022-04-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0060_auto_20220424_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='restaurants',
            field=models.ManyToManyField(blank=True, to='foodcartapp.Restaurant', verbose_name='Ресторан'),
        ),
    ]
