# Generated by Django 3.2 on 2022-04-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cords', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(verbose_name='Ширтоа')),
                ('lng', models.FloatField(verbose_name='Долгота')),
                ('creation_time', models.DateTimeField(verbose_name='Время создания')),
                ('address', models.CharField(max_length=100, verbose_name='Адресс')),
            ],
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
