# Generated by Django 3.2 on 2022-05-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cords', '0003_alter_point_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Адрес'),
        ),
    ]
