# Generated by Django 3.2 on 2022-05-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cords', '0004_alter_point_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='lat',
            field=models.FloatField(null=True, verbose_name='Ширтоа'),
        ),
        migrations.AlterField(
            model_name='point',
            name='lng',
            field=models.FloatField(null=True, verbose_name='Долгота'),
        ),
    ]
